FROM scalingo/scalingo-26

WORKDIR /app

# Install python 3.14
RUN mkdir -p /var/log/apt/
RUN apt update && apt install -y software-properties-common
RUN add-apt-repository -y ppa:deadsnakes/ppa
RUN apt update && apt install -y python3.14 python3.14-dev python3.14-venv pipx
RUN update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.14 1
RUN pipx install uv
ENV PATH="/root/.local/bin:$PATH"

# Install system dependencies
COPY Aptfile .
RUN apt install -y --no-install-recommends $(cat Aptfile)

# Install Python deps
COPY pyproject.toml .
COPY uv.lock .
ENV UV_PROJECT_ENVIRONMENT=/venv
RUN uv sync
