# Generated by Django 5.2.15 on 2026-06-18 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gesec', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField()),
                ('source_idx', models.IntegerField()),
                ('identifiant_chorus_pro', models.CharField()),
                ('numero', models.CharField()),
                ('date_etat_courant', models.DateField()),
                ('date_modification', models.DateField()),
                ('montant_a_payer', models.DecimalField(decimal_places=10, max_digits=20)),
                ('fournisseur_type_d_identifiant', models.CharField()),
                ('fournisseur_identifiant', models.CharField()),
                ('fournisseur_designation', models.CharField()),
                ('destinataire_code_service', models.CharField()),
                ('destinataire_service', models.CharField()),
                ('devise_de_la_facture', models.CharField()),
                ('numero_du_bon_de_commande', models.CharField()),
                ('numero_de_marche', models.CharField()),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
                'indexes': [models.Index(fields=['numero'], name='idx_facture_numero')],
                'constraints': [models.UniqueConstraint(fields=('identifiant_chorus_pro',), name='unique_identifiant_chorus_pro'), models.UniqueConstraint(fields=('source', 'source_idx'), name='unique_source_idx')],
            },
        ),
    ]
