# Generated by Django 5.2.15 on 2026-06-23 15:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gesec', '0002_facture'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='gm',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='facture',
            name='gm_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), null=True, size=None),
        ),
        migrations.AddField(
            model_name='facture',
            name='gm_multi',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='facture',
            index=models.Index(fields=['gm'], name='idx_facture_gm'),
        ),
    ]
