# Generated by Django 5.2.15 on 2026-06-24 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gesec', '0003_facture_gm_facture_gm_list_facture_gm_multi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='ministere',
            field=models.CharField(default='INCONNU'),
            preserve_default=False,
        ),
    ]
