# Generated by Django 5.2.15 on 2026-06-26 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gesec', '0004_facture_ministere'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='montant_remise_globale_ttc',
            field=models.DecimalField(decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='facture',
            name='montant_ttc_avant_remise',
            field=models.DecimalField(decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='facture',
            name='montant_tva',
            field=models.DecimalField(decimal_places=10, default='0', max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facture',
            name='mt_ht',
            field=models.DecimalField(decimal_places=10, default='0', max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facture',
            name='mt_ttc',
            field=models.DecimalField(decimal_places=10, default='0', max_digits=20),
            preserve_default=False,
        ),
    ]
