# Generated by Django 5.2.15 on 2026-07-20 16:30

import django.contrib.postgres.functions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gesec', '0005_facture_montant_remise_globale_ttc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateLimitCount',
            fields=[
                ('id', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField()),
                ('interval', models.IntegerField()),
                ('count', models.BigIntegerField(default=0)),
                ('expiry', models.DateTimeField()),
            ],
            options={
                'unique_together': {('key', 'interval')},
            },
        ),
    ]
